//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ChkMails.rc
//
#define IDR_MAINFRAME                   128
#define IDR_MENU_POPUP                  129
#define IDD_ACCOUNTS                    130
#define IDD_SETUP                       131
#define IDD_AUTH                        132
#define IDD_CODE                        133
#define IDD_DOMAIN                      134
#define IDD_NAME                        135
#define IDD_RECIPIENT                   136
#define IDD_SENDER                      137
#define IDD_ZONE                        138
#define IDD_WHITE                       139
#define IDI_IDLE                        140
#define IDI_BUSY                        141
#define IDI_RED                         142
#define IDI_YELLOW                      143
#define IDS_MB_INTRODUCE                150
#define IDS_MB_EXIT                     151
#define IDS_MB_POP_UNCHOSEN             152
#define IDS_MB_REEVAL                   153
#define IDS_CAPT_FILTER                 160
#define IDS_TEXT_DST_NONE               161
#define IDS_TEXT_DST_HEADER             162
#define IDS_TEXT_WHITE_ADD              163
#define IDS_TEXT_WHITE_DEL              164
#define IDS_NI_NOACCOUNTS               170
#define IDS_NI_CONNECTING               171
#define IDS_NI_FAIL_POP                 172
#define IDS_NI_FAIL_CONNECT             173
#define IDS_NI_0MAIL                    175
#define IDS_NI_1MAIL                    176
#define IDS_NI_NMAIL                    177
#define IDS_NI_REEVAL                   178
#define IDS_RF_AUTH                     200
#define IDS_RF_CHARSET                  201
#define IDS_RF_CONTROLCODE              202
#define IDS_RF_EVASIVECODE              203
#define IDS_RF_DOMAIN                   204
#define IDS_RF_FAKE_ALIAS               205
#define IDS_RF_RECIPIENT                206
#define IDS_RF_MESSAGEID                207
#define IDS_RF_CALL_BY_ADDR             208
#define IDS_RF_FAKE_DOMAIN              209
#define IDS_RF_LINK_FAKED               210
#define IDS_RF_SUBJECT_FAKED            211
#define IDS_RF_TIMEZONE                 212
#define IDS_RF_LINK_DOMAIN              213
#define IDS_RF_LINK_EVASIVE             214
#define IDS_RE_DATE                     240
#define IDS_RE_ABBR                     241
#define IDS_RE_ENCODING                 242
#define IDS_RE_ESCSEQUENCE              243
#define IDS_RE_MAIL_HEADER              244
#define IDS_RE_MULTIPART                245
#define IDS_RE_MULTIPART_BODY           246
#define IDS_RE_UNRELIABLE               247
#define IDS_RE_PASTED                   248
#define IDC_EDIT_POLL                   1001
#define IDC_CHECK_STARTUP               1002
#define IDC_COMBO_LOG                   1003
#define IDC_BUTTON_LOGPATH              1004
#define IDC_EDIT_LOGPATH                1005
#define IDC_EDIT_LOGS                   1006
#define IDC_BUTTON_TONEPATH             1007
#define IDC_EDIT_TONEPATH               1008
#define IDC_CHECK_SUMMARY               1009
#define IDC_CHECK_TONE                  1010
#define IDC_LIST_ACCOUNTS               1011
#define IDC_EDIT_SERVER                 1012
#define IDC_EDIT_USER                   1013
#define IDC_EDIT_PASS                   1014
#define IDC_CHECK_HIDE                  1015
#define IDC_RADIO_POP                   1016
#define IDC_RADIO_POPS                  1017
#define IDC_BUTTON_ADD                  1018
#define IDC_BUTTON_DELETE               1019
#define IDC_COMBO_AUTH                  1020
#define IDC_CHECK_AUTH_SENDERID         1021
#define IDC_CHECK_AUTH_SPF              1022
#define IDC_CHECK_AUTH_DKIM             1023
#define IDC_CHECK_AUTH_DMARC            1024
#define IDC_STATIC_AUTH_SENDERID        1025
#define IDC_STATIC_AUTH_SPF             1026
#define IDC_STATIC_AUTH_DKIM            1027
#define IDC_STATIC_AUTH_DMARC           1028
#define IDC_STATIC_AUTH_SAMPLE          1029
#define IDC_CHECK_CODE_CHARSET          1030
#define IDC_CHECK_CODE_CONTROL          1031
#define IDC_CHECK_CODE_EVASIVE          1032
#define IDC_LIST_DOMAIN                 1040
#define IDC_EDIT_DOMAIN                 1041
#define IDC_BUTTON_DOMAIN_ADD           1042
#define IDC_BUTTON_DOMAIN_DEL           1043
#define IDC_LIST_NAME                   1050
#define IDC_EDIT_NAME_ALIAS             1051
#define IDC_EDIT_NAME_DOMAIN            1052
#define IDC_BUTTON_NAME_ADD             1053
#define IDC_BUTTON_NAME_DEL             1054
#define IDC_CHECK_SENDER_MESSAGEID      1060
#define IDC_CHECK_SENDER_CALLALIAS      1061
#define IDC_CHECK_SENDER_FAKEUSER       1062
#define IDC_CHECK_SENDER_FAKELINK       1063
#define IDC_CHECK_SENDER_FAKESUBJECT    1064
#define IDC_LIST_RECIPIENT              1070
#define IDC_EDIT_RECIPIENT              1071
#define IDC_BUTTON_RECIPIENT_ADD        1072
#define IDC_BUTTON_RECIPIENT_DEL        1073
#define IDC_LIST_SENDER                 1074
#define IDC_EDIT_SENDER                 1075
#define IDC_BUTTON_SENDER_ADD           1076
#define IDC_BUTTON_SENDER_DEL           1077
#define IDC_LIST_TIMEZONE               1080
#define IDC_STATIC_DST                  1081
#define IDC_STATIC_LOCALTIME            1082
#define IDC_LIST_WHITE                  1090
#define IDC_BUTTON_WHITE_DEL            1091
#define IDC_STATIC_WHITE                1092
#define ID_MENU_ACCOUNTS                32771
#define ID_MENU_SETUP                   32772
#define ID_MENU_FILTER                  32773
#define ID_MENU_LOGS                    32774
#define ID_MENU_EXIT                    32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
